$wallpaper = swirly-painting.jpg

wallpaper {
    monitor = HDMI-A-1
    path = ~/arch-dotfiles/wallpapers/$wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/arch-dotfiles/wallpapers/$wallpaper
    fit_mode = cover
}
