wallpaper {
    monitor = HDMI-A-1
    path = ~/arch-dotfiles/wallpapers/frieren.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/arch-dotfiles/wallpapers/frieren.jpg
    fit_mode = cover
}
